name: Style bug report
description: Color/position errors occur after installing the theme.
labels: ["style bug"]
body:
  - type: markdown
    attributes:
      value: |
        1. Please use the latest theme and refresh the page with Ctrl+F5 to see if the Bug has disappeared.
        2. Please check the CHANGELOG.md file in the project root directory for descriptions of fixes related to this Bug.
        3. If there are related descriptions, you can check if the Bug has been fixed by compiling the development version yourself in the README.md.
        4. Please check if there is the same error in the default Gitea theme, confirming that it is not a theme problem.
  - type: input
    id: theme-version
    attributes:
      label: Theme Version
      description:
        The version of the theme, if it is a development version, you can check the value of `--theme-version` in the
        CSS file, or check the `package.json` file in the project root directory.
      placeholder: ex. 1.24.5
    validations:
      required: true
  - type: input
    id: gitea-version
    attributes:
      label: Gitea Version
      description: What version of Gitea are you using?
      placeholder: ex. 1.24.5
    validations:
      required: true
  - type: input
    id: page
    attributes:
      label: Page
      description: The page where the error occurred.
      placeholder: Issue list page
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe the actual error presentation.
      placeholder: The color of the bottom of the page is incorrect
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the expected correct presentation.
      placeholder: The color of the bottom of the page should be white
    validations:
      required: true
  - type: textarea
    id: theme-screenshot
    attributes:
      label: Screenshot of the theme applied
      description: Please upload a screenshot of the theme applied.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe how to reproduce the error.
      placeholder: 1. Install the theme 2. Refresh the page 3. View the error
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the specific presentation of the error.
      placeholder: The color of the bottom of the page is incorrect
    validations:
      required: false
  - type: textarea
    id: gitea-screenshot
    attributes:
      label: Screenshot of the default Gitea theme
      description: Please upload a screenshot of the default Gitea theme.
    validations:
      required: false
  - type: textarea
    id: github-screenshot
    attributes:
      label: Screenshot of the corresponding GitHub page
      description: Please upload a screenshot of the corresponding GitHub page.
    validations:
      required: false
