name: Feature request
description: Suggest new features.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        1. We do not accept style requests that are not Gitea or GitHub.
        2. Color requests are best implemented by yourself.
  - type: input
    id: page
    attributes:
      label: Page
      description: The page the feature involves.
      placeholder: Home page
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you want.
      placeholder: Menu style modification
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Expected theme effect.
    validations:
      required: false
  - type: textarea
    id: github-screenshot
    attributes:
      label: Screenshot of the corresponding GitHub page
      description: Please upload a screenshot of the corresponding GitHub page.
    validations:
      required: false
