name: Core bug report
description: Report errors in the theme framework.
labels: ["core bug"]
body:
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe the actual error presentation.
      placeholder: No automatic color theme generated
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the expected correct presentation.
      placeholder: Generate automatic color theme
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe how to reproduce the error.
      placeholder: 1. Create a color theme 2. Compile the theme 3. View the error
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the specific presentation of the error.
      placeholder: No automatic color theme generated
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Please upload the screenshot of the error.
    validations:
      required: false
