name: Document report
description: Improve or supplement the document.
labels: ["documentation"]
body:
  - type: textarea
    id: doc-description
    attributes:
      label: Document Description
      description: Please describe the specific content of the document.
      placeholder: The document content is incorrect
    validations:
      required: true
