name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            src:
              - ".github/workflows/*.yml"
              - "primer/**/*.ts"
              - "scripts/*"
              - "src/**/*.ts"
              - "styles/**/*.ts"
              - "themes/*.ts"
              - "theme.config.ts"
              - "vite.config.ts"
              - "package.json"

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build theme
        id: build
        if: steps.changes.outputs.src == 'true'
        run: |
          npm install
          npm run build:ci

      - name: Upload css assets
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: themes
          path: dist/*.css

      - name: Upload templates assets
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: templates
          path: templates

      - name: Build locales
        id: locales
        if: steps.build.outcome =='success'
        continue-on-error: true
        run: npm run update:locale

      - name: Upload locales assets
        if: steps.locales.outcome =='success'
        uses: actions/upload-artifact@v7
        with:
          name: locales
          path: dist/options/locale
